### ISSUE TITLE
Blue highlight doesn't show on Firefox

### ISSUE THREAD

**Issue by nylen** [nylen/d3-process-map#11]
The combination of `feColorMatrix` and `feGaussianBlur` used to highlight the active object doesn't work on Firefox :(

Code: [script.js#L159-L183](https://github.com/nylen/d3-process-map/blob/166fa6f17c97ba9eacb23ec500e0f18f8c61b4f2/script.js#L159-L183)

**Comment by bfolberth** [comment]
Anybody got a solution/workaround to this one?

**Comment by nylen** [comment]
@bfolberth I'd try removing one or both of those effects.  No time to do it myself, unfortunately, but let me know if you're able to come up with something!
