### ISSUE TITLE
Compatibility between D3.js BSD License and d3-process-map MIT license

### ISSUE THREAD

**Issue by gwpl** [nylen/d3-process-map#16]
Hi!

I'd love using your work and really appreciate you used MIT permissive license.
Please note however, that library you are using - d3 - is using BSD license.
Therefore, please coordinate with owner od d3js if is willing to move from BSD to MIT,
or consider moving on your side, due to : https://en.wikipedia.org/wiki/License_compatibility .
I am not a lawyer, but it [looks like](https://en.wikipedia.org/wiki/License_compatibility) that BSD project can use MIT code not vice versa.
Potentially you can consider hybrid -> MIT to all parts not affected by D3, than those affected to be under BSD. (Most permissive approach, but loosing clarity and in practice - boiling down to BSD as common denominator anyway)

Again, Thanks for work!
Best regards!
Grzegorz Wierzowiecki

**Comment by nylen** [comment]
The license incompatibilities that I am aware of involve the GPL and other [viral licenses](https://en.wikipedia.org/wiki/Viral_license) that impose requirements on code that uses GPL libraries.  Neither the BSD nor MIT licenses contain any such restrictions:

> Permissive licences (BSD, MIT, X11, Apache, Zope) are generally compatible and interoperable with most other licences, tolerating to merge, combine or improve the covered code and to re-distribute it under many licences (including non-free or “proprietary”).

-- https://joinup.ec.europa.eu/community/eupl/og_page/licence-compatibility
