### ISSUE TITLE
How to change rect text color?

### ISSUE THREAD

**Issue by alexj28** [nylen/d3-process-map#23]
I am attempting to change the text color in the rect objects and have changed the .node text { color: property in the svg.css file. However, some bug is preventing the text color from changing. I would appreciate any help I could get with this. 

Thank you.

**Comment by nylen** [comment]
Hi @alexj28,

SVG elements are styled a bit differently from other HTML elements.  You need to use the `fill` property to accomplish this, `fill: red;` for example.

See also:  https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text#Styling_text_via_CSS
